

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RubenGuillermo
 */
public class SDES extends javax.swing.JFrame  {
    
     
    
    
        public class DES {
            
        public int K1, K2;
        public  final int P10[] = { 3, 5, 2, 7, 4, 10, 1, 9, 8, 6};
        public  final int P10max = 10;
        public  final int P8[] = { 6, 3, 7, 4, 8, 5, 10, 9};
        public  final int P8max = 10;
        public  final int P4[] = { 2, 4, 3, 1};
        public  final int P4max = 4;
        public  final int IP[] = { 2, 6, 3, 1, 4, 8, 5, 7};
        public  final int IPmax = 8;
        public  final int IPI[] = { 4, 1, 3, 5, 7, 2, 8, 6};
        public  final int IPImax = 8;
        public  final int EP[] = { 4, 1, 2, 3, 2, 3, 4, 1};
        public  final int EPmax = 4;
        public  final int S0[][] = {{ 1, 0, 3, 2},{ 3, 2, 1, 0},{ 0, 2, 1,3},{ 3, 1, 3, 2}};
        public  final int S1[][] = {{ 0, 1, 2, 3},{ 2, 0, 1, 3},{ 3, 0, 1, 2},{ 2, 1, 0, 3}};
       
       private  int permute( int x, int p[], int pmax) {
         int y = 0;
         for( int i = 0; i < p.length; ++i)
          {
            y <<= 1;
            y |= (x >> (pmax - p[i])) & 1;
        }
         return y;
       }
       
       public  int F( int R, int K){
           
          int t = permute( R, EP, EPmax) ^ K;
          int t0 = (t >> 4) & 0xF;
          int t1 = t & 0xF;
          t0 = S0[ ((t0 & 0x8) >> 2) | (t0 & 1) ][ (t0 >> 1) & 0x3 ];
          t1 = S1[ ((t1 & 0x8) >> 2) | (t1 & 1) ][ (t1 >> 1) & 0x3 ];
           t = permute( (t0 << 2) | t1, P4, P4max);
         return t;
       
        }

  public  int fK( int m, int K)
        {
            int L = (m >> 4) & 0xF;
            int R = m & 0xF;
            return ((L ^ F(R,K)) << 4) | R;
        }
       
  public  int SW( int x)
  {
   return ((x & 0xF) << 4) | ((x >> 4) & 0xF);
  }
       
       
        public byte encrypt( int m) {
          
          m = permute( m, IP, IPmax);
         
          m = fK( m, K1);
          
          m = SW( m);
         
          m = fK( m, K2);
          
          m = permute( m, IPI, IPImax);
          return (byte) m;
        }
       
       
        public byte decrypt( int m) {
            
          m = permute( m, IP, IPmax);
          
          m = fK( m, K2);
          
          m = SW( m);
          
          m = fK( m, K1);
          
          m = permute( m, IPI, IPImax);
          
          return (byte) m;  
        }
       
        public  void printData( int x, int n){
           int mask = 1 << (n-1);
           while( mask > 0)
           {
          
               System.out.print(( ((x & mask) == 0) ? "0" : "1"));
               
               
           mask >>= 1;
           }
        }
       
       
       
        public DES( int K)
      {
          K = permute( K, P10, P10max);
          int t1 = (K >> 5) & 0x1F;
          int t2 = K & 0x1F;
          t1 = ((t1 & 0xF) << 1) | ((t1 & 0x10) >> 4);
          t2 = ((t2 & 0xF) << 1) | ((t2 & 0x10) >> 4);
          K1 = permute( (t1 << 5)| t2, P8, P8max);
          t1 = ((t1 & 0x7) << 2) | ((t1 & 0x18) >> 3);
          t2 = ((t2 & 0x7) << 2) | ((t2 & 0x18) >> 3);
          K2 = permute( (t1 << 5)| t2, P8, P8max);
       
        }
       
      }
    
    
    
    
    
    
    
    public void printEncrypted( int x, int n){
           int mask = 1 << (n-1);
           while( mask > 0)
           {
           String m =  ((x & mask) == 0) ? "0" : "1" ;
            Emessage.append(((x & mask) == 0) ? "0" : "1");
           mask >>= 1;
           }
        }
    
    public void printDecrypted(int x , int n){
           int mask = 1 << (n-1);
           while( mask > 0)
           {
           String m = ((x & mask) == 0) ? "0" : "1";
            Dmessage.append(((x & mask) == 0) ? "0" : "1");
           mask >>= 1;
           }
    
    }

    /**
     * Creates new form SDES
     */
    public SDES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plaintext = new javax.swing.JTextField();
        key = new javax.swing.JTextField();
        ciphertext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        decrypt = new javax.swing.JButton();
        encrypt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dmessage = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Emessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(null);
        getContentPane().add(plaintext);
        plaintext.setBounds(30, 40, 80, 30);

        key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyActionPerformed(evt);
            }
        });
        getContentPane().add(key);
        key.setBounds(150, 40, 100, 30);
        getContentPane().add(ciphertext);
        ciphertext.setBounds(290, 40, 100, 30);

        jLabel1.setText("PlainText");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 16, 60, 16);

        jLabel2.setText("Key");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(175, 16, 40, 16);

        jLabel3.setText("CipherText");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 16, 70, 16);

        decrypt.setText("Decrypt");
        decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptActionPerformed(evt);
            }
        });
        getContentPane().add(decrypt);
        decrypt.setBounds(30, 260, 90, 28);

        encrypt.setText("Encrypt");
        encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });
        getContentPane().add(encrypt);
        encrypt.setBounds(30, 140, 90, 28);

        jLabel4.setText("Encrypted Message");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 84, 130, 20);

        jLabel5.setText("Decrypted Message");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 210, 110, 16);

        Dmessage.setColumns(20);
        Dmessage.setRows(5);
        jScrollPane1.setViewportView(Dmessage);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 230, 250, 130);

        Emessage.setColumns(20);
        Emessage.setRows(5);
        jScrollPane2.setViewportView(Emessage);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 106, 250, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyActionPerformed

    private void encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptActionPerformed
     Emessage.setText(null);
    int k = Integer.parseInt(key.getText(),2);
     DES A = new DES(k);
     int m = Integer.parseInt(plaintext.getText(),2);
     m = A.encrypt(m);
     printEncrypted(m,8);
     //m = A.decrypt(m);
     //printDecrypted(m,8);
    }//GEN-LAST:event_encryptActionPerformed

    private void decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptActionPerformed
    Dmessage.setText(null);
     int k = Integer.parseInt(key.getText(),2);
     DES A = new DES(k);
     int m = Integer.parseInt(plaintext.getText(),2);
     m = A.encrypt(m);
     m = A.decrypt(m);
     printDecrypted(m,8);
    }//GEN-LAST:event_decryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Dmessage;
    private javax.swing.JTextArea Emessage;
    private javax.swing.JTextField ciphertext;
    private javax.swing.JButton decrypt;
    private javax.swing.JButton encrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField key;
    private javax.swing.JTextField plaintext;
    // End of variables declaration//GEN-END:variables
}
